
import React from 'react';
import type { GeneratedImageResult } from '../types';

interface ImageResultsProps {
    results: GeneratedImageResult[];
}

const ImageResults: React.FC<ImageResultsProps> = ({ results }) => {
    if (!results || results.length === 0) {
        return null;
    }

    return (
        <div className="w-full max-w-5xl mx-auto mt-8">
            <h2 className="text-2xl font-semibold text-slate-200 mb-2">
                Generated Images for: <span className="text-cyan-400">"{results[0].prompt}"</span>
            </h2>
            <p className="text-sm text-slate-400 mb-6">These images were generated by AI based on your prompt.</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {results.map((result, index) => (
                    <div key={index} className="bg-slate-800/50 rounded-lg overflow-hidden border border-slate-700 transform transition-transform duration-300 hover:scale-105 hover:shadow-2xl hover:shadow-cyan-500/10">
                        <img
                            src={result.imageUrl}
                            alt={`AI-generated image for prompt: ${result.prompt}`}
                            className="w-full h-auto object-cover"
                        />
                    </div>
                ))}
            </div>
        </div>
    );
};

export default ImageResults;
